
name: Hello World for Selfhost

on: 
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - run: javac C:\Users\Administrator\Desktop\HelloWorld.java -d C:\Users\Administrator\Desktop
      - run: java HelloWorld -classpath C:\Users\Administrator\Desktop
