
name: Hello World for Selfhost

on: push

jobs:
  say_hello:
    runs-on: self-hosted
    steps:
      - run: javac HelloWorld.java -d C:\Users\Administrator\Desktop
      - run: java -classpath C:\Users\Administrator\Desktop HelloWorld
